### ISSUE TITLE
Update adrenaline

### ISSUE THREAD

**Issue by bmob222** [MLTHaKu/MLTHaKu#2]
Can you update vitashell and adrenaline please? Thanks for your amazing work !!

**Comment by Darkmet98** [comment]
Ready ;)
https://github.com/MLTHaKu/MLTHaKu-Web/commit/d2a8057142bb1125b620bfbf102abce0456f5dfa

**Comment by bmob222** [comment]
Your the best link for donations ?

**Comment by Darkmet98** [comment]
Nope, thanks, but is not necessary any donations for our work ^^
